[package]
authors = ["LongYinan <lynweklm@gmail.com>"]
edition = "2021"
name = "nosql"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi-derive = "3.0.0"
serde = "1.0.229"
serde_derive = "1.0.229"
serde_json = "1.0.151"
nosql = { path = "/Users/lucas11776/Desktop/Personal/simple-database/" }

[dependencies.napi]
version = "3.0.0"
features = ["napi4", "tokio_rt", "serde-json"]

[build-dependencies]
napi-build = "2"

[profile.release]
lto = true
strip = "symbols"