/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Collection {

}

export declare class Database {
  static open(path: string): Promise<Database>
  collection(name: string): Promise<Collection>
  create(collection: string): Promise<void>
  rename(collectionOld: string, collectionNew: string): Promise<void>
  delete(name: string): Promise<void>
  has(collection: string): Promise<boolean>
  list(): Promise<Array<string>>
  close(): Promise<void>
}
