/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Collection {
  insertOne(doc: any): Promise<InsertResult>
  insertMany(docs: Array<any>): Promise<Array<InsertResult>>
  findOne(filter: any): Promise<any | null>
  update(filter: any, update: any): Promise<UpdateResult>
}

export declare class Database {
  static open(path: string): Promise<Database>
  collection(name: string): Promise<Collection>
  create(collection: string): Promise<void>
  rename(collectionOld: string, collectionNew: string): Promise<void>
  delete(name: string): Promise<void>
  has(collection: string): Promise<boolean>
  list(): Promise<Array<string>>
  close(): Promise<void>
}

export declare class DeleteResult {
  deletedCount: number
}

export interface InsertResult {
  insertedId: any
}

export interface RecordId {
  pageId: number
  slotId: number
}

export interface UpdateResult {
  matchedCount: number
  modifiedCount: number
}
